# Generated by Django 5.1.4 on 2026-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Номер задачи'),
        ),
    ]
